name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deny:
    name: Cargo deny
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo install cargo-deny
      - run: cargo deny check

  test-mac:
    name: Cargo test on Mac
    strategy:
      # Only have one combination, because the Mac setup is too flaky
      matrix:
        os:
          - macOS-latest
        toolchain:
          - 1.68
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: cargo clippy
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast

  test-nix:
    name: Cargo test on nix
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - 1.68
          - beta
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: docker version
      - run: cargo clippy
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast

  test-windows:
    name: Cargo test on Windows
    strategy:
      matrix:
        os:
          - windows-2022
        toolchain:
          - 1.68
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
